// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEmuyjqyWQpnRF3zDwtJJGjBNGLW4hds',
    appId: '1:658178757291:web:9b36410d50b9cd93d11dee',
    messagingSenderId: '658178757291',
    projectId: 'flutterfirebaseauthui202-7da9a',
    authDomain: 'flutterfirebaseauthui202-7da9a.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthui202-7da9a.firebasestorage.app',
    measurementId: 'G-3TJY7JGH88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOYQJmX_ZNNF-6dxwJMp6NDO0DIxnzHk',
    appId: '1:658178757291:android:e37a653ccf95d4c4d11dee',
    messagingSenderId: '658178757291',
    projectId: 'flutterfirebaseauthui202-7da9a',
    storageBucket: 'flutterfirebaseauthui202-7da9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXkvNJ4E73VVU2YvCS0CTB5HgHwDuQpo',
    appId: '1:658178757291:ios:10fbc812ea2fb5a2d11dee',
    messagingSenderId: '658178757291',
    projectId: 'flutterfirebaseauthui202-7da9a',
    storageBucket: 'flutterfirebaseauthui202-7da9a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOXkvNJ4E73VVU2YvCS0CTB5HgHwDuQpo',
    appId: '1:658178757291:ios:10fbc812ea2fb5a2d11dee',
    messagingSenderId: '658178757291',
    projectId: 'flutterfirebaseauthui202-7da9a',
    storageBucket: 'flutterfirebaseauthui202-7da9a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWEmuyjqyWQpnRF3zDwtJJGjBNGLW4hds',
    appId: '1:658178757291:web:6a3ec69a5d1486ded11dee',
    messagingSenderId: '658178757291',
    projectId: 'flutterfirebaseauthui202-7da9a',
    authDomain: 'flutterfirebaseauthui202-7da9a.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthui202-7da9a.firebasestorage.app',
    measurementId: 'G-WDEFFGK7YF',
  );
}
